version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis-socket
    command: [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    volumes:
      - reddata:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - universe
  backend:
    container_name: universe-backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - backend-node-modules:/usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${AUCTIONS_SOCKET_PORT}:${AUCTIONS_SOCKET_PORT}
      - 9229:9229
    command: ./docker/dev.command.sh
    env_file:
      - .env
    networks:
      - universe
    depends_on:
      - postgres-universe-external
      - redis
  postgres-universe-external:
    container_name: postgres-universe-external
    image: postgres:12.2
    networks:
      - universe
    environment:
      TZ: GMT
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  universe:
    external: true
    name: universe-network
volumes:
  backend-node-modules:
  pgdata:
  reddata: