version: '3.7'

services:
  backend:
    container_name: universe-backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - backend-node-modules:/usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: ./docker/dev.command.sh
    env_file:
      - .env
    networks:
      - universe
networks:
  universe:
    external: true
    name: universe-network
volumes:
  backend-node-modules: