import { IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class LoginBody {
  @IsString()
  @ApiProperty({
    example: '0x0000',
    description: 'The wallet public address',
    required: true,
  })
  address: string;

  @IsString()
  @ApiProperty({
    example: '0x0000',
    description: 'The signed challenge',
    required: true,
  })
  signature: string;

  @IsString()
  @ApiProperty({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'The uuid of the challenge',
    required: true,
  })
  uuid: string;
}

export class SetChallengeBody {
  @IsString()
  @ApiProperty({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'The challenge generated by the client',
    required: true,
  })
  challenge: string;
}

export class SetChallengeResponse {
  @ApiProperty({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'The uuid of the registered challenge',
  })
  uuid: string;
}
