import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

@Entity({
  schema: 'universe-backend',
})
export class RewardTierNft {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  rewardTierId: number;

  @Column()
  nftId: number;

  //this is populated by the eth events crons, using events generated by the auction contract
  @Column({ default: false })
  deposited: boolean;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
