import { Exclude } from 'class-transformer';
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity()
export class RewardTierNft {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  rewardTierId: number;

  @Column()
  nftId: number;

  //this is populated by the eth events crons, using events generated by the auction contract
  @Column({default: false})
  deposited: boolean;

  @CreateDateColumn()
  @Exclude()
  createdAt: Date;

  @UpdateDateColumn()
  @Exclude()
  updatedAt: Date;
}
